### PR TITLE
Upgrade AWS SDK to 3.x

### PR DESCRIPTION
**Pull request by Offspring2099**
See: https://github.com/RecycledMedia/tradesy-common/pull/4681

### CODE REVIEW

**Review by nanodocumet — APPROVED** [review]
lgtm

**Comment by ehongyu** [comment]
Jorge, I just received some PRs from Tradesy in my mailbox today. Probably
my account hasn't been removed from some of the rarely used repos. I
attached the list of those repos in this email. I would definitely be happy
to be still involved, but just don't want anything bad happening if some
not-so-friendly former employees have the same right as mine ;)

**Comment by alexlivenson** [comment]
I also got a bunch of emails from these repos

**Comment by dstynchula** [comment]
Hi Alex!
Long time no see mang!

Dan Stynchula

**Comment by alexlivenson** [comment]
Sup dude!

**Comment by Offspring2099** [comment]
Hello friends!

Hope all are doing well, good to hear from you.

I believe this is a fork from Matts public repo, so Tradesy's fork is
public as well, and you all are "watchers" on th repo.  Please go to the
repo and click "watch" to unwatch.

Dmitriy

**Pull request merged**
